spring:
  application:
    name: "flight-service"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-message: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
