spring:
  application:
    name: 'flight-service'
  config:
    import: configserver:http://config-server:8061
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_DSN}
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8003
  error:
    include-message: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}